name: trip_mint
description: Travel Budget Planner Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Image Picker (for camera & gallery)
  image_picker: ^1.0.7
  
  # HTTP for uploading to Cloudinary
  http: ^1.2.0
  
  # Path provider (for file handling)
  path_provider: ^2.1.2
  
  # State Management
  provider: ^6.1.5+1
  
  # Existing packages
  intl: ^0.19.0
  fl_chart: ^0.66.2 # chart
  uuid: ^4.5.2
  
  # ðŸ”¥ FIREBASE BACKEND (FIXED VERSIONS)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1

  # âœ… NEW: PDF GENERATION
  pdf: ^3.11.1
  printing: ^5.13.1
  
  # âœ… NEW: SHARING
  share_plus: ^10.1.2
  
  # âœ… NEW: SCREENSHOTS (for charts in PDF)
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  android: true
  image_path: "assets/icons/trip_logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/trip_mint_logo.png